# Generated by Django 5.1.4 on 2025-05-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_converted_to_client_alter_lead_name'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='teams.team'),
            preserve_default=False,
        ),
    ]
